basket/urls.py
from django.urls import path
from . import views

app_name='basket'

urlpatterns = [
    path('',views.basket_summary,name='basket_summary'),
    path('add/',views.basket_add,name='basket_add'),
    path('update/', views.basket_update, name='basket_update'),
    path('delete/', views.basket_delete, name='basket_delete'),
]

ecom/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls' ,namespace='shop')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='index'),
    path('products/<slug:slug>/',views.ProductDetailView.as_view(),name='product-detail'),
    path('category/<slug:category_slug>/',views.CategoryProductView.as_view(),name='category-list'),
]

shop/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from PIL import Image

class ProductManager(models.Manager):
	def get_queryset(self):
		return super(ProductManager,self).get_queryset().filter(is_active=True)


class Category(models.Model):
	name=models.CharField(max_length=200,blank=True,null=True,db_index=True)
	slug=models.SlugField(max_length=200,unique=True,blank=True,null=True)

	class Meta:
		verbose_name_plural = 'categories'

	def get_absolute_url(self):
		return reverse('shop:category-list', args=[self.slug])

	def __str__(self):
		return self.name


class Product(models.Model):
	category=models.ForeignKey(Category,related_name='product',on_delete=models.CASCADE,blank=True,null=True)
	created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator', blank=True, null=True)
	title=models.CharField(max_length=200,blank=True,null=True)
	author=models.CharField(max_length=200,default='admin',blank=True,null=True)
	slug=models.SlugField(max_length=200,unique=True,blank=True,null=True)
	description = models.TextField(blank=True,null=True)
	image=models.ImageField(upload_to='thumbnails/')
	price=models.DecimalField(max_digits=10,decimal_places=2)
	in_stock=models.BooleanField(default=True)
	is_active=models.BooleanField(default=True)
	created=models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	objects = models.Manager()
	products = ProductManager()

	class Meta:
		ordering=['-created']
	
	def get_absolute_url(self):
		return reverse('shop:product-detail',args=[self.slug])

	def __str__(self):
		return self.title

basket/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from .basket import Basket
from shop.models import Product

@login_required
def basket_summary(request):
    basket=Basket(request)
    return render(request,'shop/basket/summary.html',{'basket':basket})

def basket_add(request):
    basket = Basket(request)

    if request.POST.get('action') == 'post':
        product_id=int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product,id=product_id)
        basket.add(product=product, qty=product_qty)
        basketqty = basket.__len__()
        response = JsonResponse({'qty':basketqty})
        return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id,qty=product_qty)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        print(baskettotal)

        response = JsonResponse({'qty':basketqty,'subtotal':baskettotal})
        return response


def basket_delete(request):
    basket = Basket(request)

    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)
        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.template.defaultfilters import slugify
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from .models import Product, Category


class ProductListView(ListView):
	model = Product
	template_name='index.html'
	context_object_name='products'
	paginate_by=8

	def get_queryset(self):
		return Product.products.all()

class ProductDetailView(DetailView):
	model=Product
	template_name='shop/product.html'
	context_object_name='product'


class CategoryProductView(ListView):
	model = Category
	template_name = 'shop/category.html'
	paginate_by=8

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		category = get_object_or_404(Category, slug=self.kwargs['category_slug'])
		context["category"] = category
		context["products"] = Product.products.filter(category=category) 
		return context
	
	

	

templates/shop/basket/summary.html
{% extends 'base.html' %}

{% block title %}
Cart Summary
{% endblock %}

{% block content %}
    <h1 class='mb-3'>Shopping Cart</h1>
    {% if basket|length == 0 %}
        <p class='alert alert-info'>Your Cart is empty! <a href="{% url 'shop:index' %}" class='text-info'>Shop</a></p>
    {% else %}

    <div class="row">

        <div class="col-md-8">

            <ul class="list-group list-group-flush">
            {% for item in basket %}
            {% with product=item.product %}
                <li data-index="{{product.id}}" class="list-group-item product-item">
                    <div class="row">
                        <div class="col-md-2">
                            <img src="{{product.image.url}}" alt=product.title class='img-fluid rounded'>
                        </div>
                        <div class="col-md-3">
                            <a href="{{product.get_absolute_url}}" class="text-decoration-none">{{product.title}}</a>
                        </div>
                        <div class="col-md-2">₹&nbsp;{{product.price}}</div>
                        <div class="col-md-2">
                            <select id="select{{product.id}}" class='form-control'>
                                <option selected hidden>
                                    {{item.qty}}
                                </option>
                                <option value="">1</option>
                                <option value="">2</option>
                                <option value="">3</option>
                                <option value="">4</option>
                            </select>
                        </div>
                        <div class="col-md-1">
                            <button type="button" id="update-button" data-index="{{product.id}}"
                                class="btn btn-link btn-sm update-button text-info" title='Update product qunatity'>
                                <i class="fas fa-check"></i>
                            </button> 
                        </div>
                        <div class="col-md-1">
                            <button type="button" id="delete-button" data-index="{{product.id}}"
                                class="btn btn-link btn-sm delete-button" title='Remove from cart'>
                                <i class="fas fa-trash"></i>
                            </button>                            
                        </div>
                    </div>
                </li>
            {% endwith %}
            {% endfor %}
            </ul>

        </div>

        <div class="col-md-4">
            <div class="card mb-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <h2>
                            <div>Sub Total ({{basket|length}}) item{{basket|length|pluralize}}:</div> 
                            <div id="subtotal">₹&nbsp;{{basket.get_total_price}}</div>
                        </h2>
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'payment:basket' %}" class="btn btn-info btn-block" role='button'>Checkout</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    {% endif %}

    <script>
  // Delete Item
  $(document).on('click', '.delete-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_delete" %}',
      data: {
        productid: $(this).data('index'),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();
        document.getElementById("subtotal").innerHTML = json.subtotal;
        document.getElementById("basket-qty").innerHTML = json.qty
        location.reload(true)
      },
      error: function (xhr, errmsg, err) {}
    });
  })

  // Update Item
  $(document).on('click', '.update-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_update" %}',
      data: {
        productid: $(this).data('index'),
        productqty: $('#select' + prodid + ' option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        document.getElementById("basket-qty").innerHTML = json.qty
        document.getElementById("subtotal").innerHTML = json.subtotal
        location.reload(true)
      },
      error: function (xhr, errmsg, err) {}
    });
  })
</script>

{% endblock %}