account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView
from .forms import UserLoginForm, PwdResetForm, PwdResetConfirmForm
from . import views

app_name = 'account'

urlpatterns = [
    #authentication

    path('login/',auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                               form_class=UserLoginForm, redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='account:login'), name='logout'),
    path('register/',views.account_register,name='register'),
    path('activate/<slug:uidb64>/<slug:token>/',views.account_activate,name='activate'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='account/user/password_reset_form.html',
                                                                success_url='password_reset_email_confirm',
                                                                email_template_name='account/user/password_reset_email.html',
                                                                form_class=PwdResetForm),name="pwdreset"),

    path('password_reset_confirm/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(
                                                                template_name='account/user/password_reset_confirm.html',
                                                                success_url='password_reset_complete',
                                                                form_class=PwdResetConfirmForm),name='password_reset_confirm'),
    
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_confirm/Mg/password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
    
    
    # user dashboard

    path('dashboard/',views.dashboard,name='dashboard'),
    path('profile/edit/',views.edit_details,name='edit_details'),
    path('profile/delete_user/',views.delete_user,name='delete_user'),
    path('profile/delete_confirm/',
         TemplateView.as_view(template_name='account/user/delete_confirm.html'), name='delete_confirmation'),
    
]

basket/urls.py
from django.urls import path
from . import views

app_name='basket'

urlpatterns = [
    path('',views.basket_summary,name='basket_summary'),
    path('add/',views.basket_add,name='basket_add'),
    path('update/', views.basket_update, name='basket_update'),
    path('delete/', views.basket_delete, name='basket_delete'),
]

ecom/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls' ,namespace='shop')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='index'),
    path('products/<slug:slug>/',views.ProductDetailView.as_view(),name='product-detail'),
    path('category/<slug:category_slug>/',views.CategoryProductView.as_view(),name='category-list'),
]

shop/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from PIL import Image

class ProductManager(models.Manager):
	def get_queryset(self):
		return super(ProductManager,self).get_queryset().filter(is_active=True)


class Category(models.Model):
	name=models.CharField(max_length=200,blank=True,null=True,db_index=True)
	slug=models.SlugField(max_length=200,unique=True,blank=True,null=True)

	class Meta:
		verbose_name_plural = 'categories'

	def get_absolute_url(self):
		return reverse('shop:category-list', args=[self.slug])

	def __str__(self):
		return self.name


class Product(models.Model):
	category=models.ForeignKey(Category,related_name='product',on_delete=models.CASCADE,blank=True,null=True)
	created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator', blank=True, null=True)
	title=models.CharField(max_length=200,blank=True,null=True)
	author=models.CharField(max_length=200,default='admin',blank=True,null=True)
	slug=models.SlugField(max_length=200,unique=True,blank=True,null=True)
	description = models.TextField(blank=True,null=True)
	image=models.ImageField(upload_to='thumbnails/')
	price=models.DecimalField(max_digits=10,decimal_places=2)
	in_stock=models.BooleanField(default=True)
	is_active=models.BooleanField(default=True)
	created=models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	objects = models.Manager()
	products = ProductManager()

	class Meta:
		ordering=['-created']
	
	def get_absolute_url(self):
		return reverse('shop:product-detail',args=[self.slug])

	def __str__(self):
		return self.title

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.template.defaultfilters import slugify
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from .models import Product, Category


class ProductListView(ListView):
	model = Product
	template_name='index.html'
	context_object_name='products'
	paginate_by=8

	def get_queryset(self):
		return Product.products.all()

class ProductDetailView(DetailView):
	model=Product
	template_name='shop/product.html'
	context_object_name='product'


class CategoryProductView(ListView):
	model = Category
	template_name = 'shop/category.html'
	paginate_by=8

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		category = get_object_or_404(Category, slug=self.kwargs['category_slug'])
		context["category"] = category
		context["products"] = Product.products.filter(category=category) 
		return context
	
	

	

templates/shop/carousel.html
{% load static %}
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    {% for product in carousel_product %}
    <div class="carousel-item active">
      <img src="{{product.image.url}}" class="d-block w-100" alt="..." width="320" height="240">
      <div class="carousel-caption d-none d-md-block">
        <h5>{{product.name}}</h5>
        <p>{{product.description}}.</p>
      </div>
    </div>
    {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

templates/shop/category.html
{% extends '../base.html' %}

{% block title %}
Books in {{category.name|title}}
{% endblock %}

{% block content %}

        <form action="" method="get" class="form mb-4">
          <div class="input-group mb-3">
            <input type="Search" class="form-control" placeholder="Search Books" />
            <div class="input-group-append">
              <button class="btn btn-outline-primary btn-sm" type="submit">
                <i class="fas fa-search"></i>
              </button>
            </div>
          </div>
        </form>

        <h1>Latest Books in {{category.name|title}}</h1>

<div class="row">

  {% for product in products %}
  <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">

    <div class="card shadow-sm my-3 p-3 rounded">
      <a href="{{product.get_absolute_url}}">
        <img src="{{product.image.url}}" alt="" class="card-img-top image-fluid">
      </a>
      <div class="card-body">
        <div class="cad-title">
        {% if product.title|length <= 20 %}
          <h5 class='my-2'><a class="text-decoration-none text-dark" href="{{product.get_absolute_url}}" title='{{product.title}}'>{{product.title}}</a></h5>
        {% else %}
          <h5 class='my-2'><a class="text-decoration-none text-dark" href="{{product.get_absolute_url}}" title='{{product.title}}'>{{product.title|slice:17}}...</a></h5>
        {% endif %}
          <small class='text-muted'>{{product.author}}</small>
        </div>
        <div class="card-text my-2">{{product.description|slice:30}}...</div>
        <div class="card-text">
          <h3 class='mt-3 text-right'>₹{{product.price}}</h3>
        </div>
      </div>
    </div>

  </div>
  {% endfor %}
</div>

<!-- Pagination -->

{% include 'shop/pagination.html' %}

{% endblock %}

templates/shop/category_list.html
<div class="list-group">
  <div class="card shadow-sm my-2">
    <div class="card-body">
      <h5>Categories</h5>
      <ul class="list-group">
      {% for category in category_list %}
        <li class="list-group-item">{{category.name|title}}</li>
      {% endfor %}
      </ul>
    </div>
  </div>
</div>

templates/shop/footer.html
  <footer class="py-3 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Avishek Das 2021</p>
    </div>
    <!-- /.container -->
  </footer>

templates/shop/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'shop:index' %}">Book<span class='text-danger'>Store</span></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Categories</a>
        <div class="dropdown-menu">
          {% for category in category_list%}
          <a class="dropdown-item" href="{{category.get_absolute_url}}"><i class="fas fa-stream"></i>&nbsp;{{category.name|title}}</a>
          {% endfor %}
        </div>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class='fas fa-user-alt'></i>&nbsp;Hello, {{request.user}}</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'account:dashboard' %}"><i class='fas fa-user-cog'></i>&nbsp;Dashboard</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'account:logout' %}"><i class="fas fa-sign-out-alt"></i>&nbsp;Logout</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'basket:basket_summary' %}"><i class='fas fa-shopping-cart'></i>
          &nbsp;Cart
          {% with total_qty=basket|length %}
          <sup>
          <span class='badge badge-danger badge-pill' id='basket-qty'>
          {% if total_qty > 0 %}
          {{total_qty}}
          {% else %}
          0
          {% endif %}
          </span>
          </sup>
          {% endwith %}
        </a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:login' %}"><i class="fas fa-sign-in-alt"></i>&nbsp;Login
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn btn-outline-warning btn-sm" href="{% url 'account:register' %}"><i class="fas fa-user-plus"></i>&nbsp;Register
        </a>
      </li>
      {% endif %}
  </div>
</nav>

templates/shop/pagination.html
<div class="text-center">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
                <a href="?page=1" class="btn btn-outline-info mb-4">First</a>
                <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info mb-4">Previous</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                    <a href="?page={{num}}" class="btn btn-info mb-4 disabled">{{num}}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a href="?page={{num}}" class="btn btn-outline-info mb-4">{{num}}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}" class="btn btn-outline-info mb-4">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-info mb-4">Last</a>
        {% endif %}
    {% endif %}
</div>

templates/shop/product.html
{% extends '../base.html' %}

{% block title %}
{{product.title}}
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <img src="{{product.image.url}}" alt="" class="img-fluid border">
    </div>

    <div class="col-md-3">
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><h3>{{product.title}}</h3></li>
            <li class="list-group-item">Author: {{product.author}}</li>
            <li class="list-group-item">Price: ₹{{product.price}}</li>
            <li class="list-group-item">Description: {{product.description|linebreaks}}</li>
        </ul>
    </div>

    <div class="col-md-3">
        <ul class="list-group list-group mb-3">
            <li class="list-group-item">
                <div class="row">
                    <div class="col">Price: </div>
                    <div class="col"><strong>₹{{product.price}}</strong></div>
                </div>
            </li>
            <li class="list-group-item">
                <div class="row">
                    <div class="col">Status: </div>
                    <div class="col">
                        {% if product.in_stock %}
                        In stock
                        {% else %}
                        Out of stock
                        {% endif %}
                    </div>
                </div>
            </li>
            <li class="list-group-item">
                <div class="row">
                    <div class="col">Quantity: </div>
                    <div class="col">
                        {% if product.in_stock %}
                        <select class="form-control" id='select'>
                            <option selected>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                        </select>
                        {% else %}
                        <select class="form-control" disabled>
                            <option selected>0</option>
                        </select>  
                        {% endif %}                      
                    </div>
                </div>
            </li>
            <li class="list-group-item">
                {% if product.in_stock %}
                <button type='button' id='add-button' value="{{product.id}}" class="btn btn-info btn-block">Add to cart</button>
                {% else %}
                <button type='button' class="btn btn-primary btn-block" disabled>Add to cart</button>
                {% endif %}
            </li>
        </ul>        
    </div>
</div>

<script>
    $(document).on('click','#add-button',function(e){
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function(json){
                document.getElementById('basket-qty').innerHTML = json.qty
                location.replace("{% url 'basket:basket_summary' %}")
            },
            error: function(xhr,errmsg,err){}
        });
    });
</script>
{% endblock %}